In [8]:
import pandas as pd

In [9]:
import os

print(os.getcwd())

/home/mdumar/data_eng/projects/olist-pandas-pipeline/notebooks

In [10]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

In [11]:
from config import BRONZE_PATH

df = pd.read_parquet(BRONZE_PATH / "olist_customers_dataset.parquet")

In [ ]:
df.info()
df.head()

In [ ]:
df = pd.read_parquet("../output/bronze/orders.parquet")

print(df.info())

display(df.head())

display(df.describe(include="all"))

print(df.isna().sum())

print(df.duplicated().sum())

<!-- ========================================================================= -->
olist_order_items_dataset.parquet

In [ ]:
df3 = pd.read_parquet("../output/bronze/olist_order_items_dataset.parquet")

In [ ]:
df3.info()

In [ ]:
df3.head()

In [ ]:
display(df3.describe(include="all"))

In [ ]:

print(df3.isna().sum())

In [ ]:
print(df3.duplicated().sum())

cheacking trensfromtioin is working or not

In [ ]:
df4 = pd.read_parquet("../output/silver/olist_order_items_dataset.parquet")

print(df4.info())

-----------------------------------------------------------------
===============  olist_products_dataset.parquet  check =================

In [ ]:
olist_products = pd.read_parquet("../output/silver/olist_products_dataset.parquet")

In [ ]:
olist_products.info()

In [ ]:
olist_products.head()

In [ ]:
display(olist_products.describe(include="all"))

In [ ]:
print(olist_products.isna().sum())

In [ ]:
print(olist_products.duplicated().sum())

In [ ]:
missing_products = olist_products[olist_products["product_category_name"].isna()]

print(missing_products.head())

print(missing_products.shape)

In [ ]:
text_columns = df.select_dtypes(include="object").columns

for column in text_columns:
    print(f"\nChecking: {column}")
    print(df[column].str.startswith(" ").sum())
    print(df[column].str.endswith(" ").sum())


#  replacing product catogery name with unkonwn

In [ ]:
import pandas as pd

df = pd.read_parquet("output/silver/olist_products_dataset.parquet")

In [ ]:
import os

print(os.getcwd())
import os

print(os.listdir())

In [12]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

from config import SILVER_PATH

df = pd.read_parquet(SILVER_PATH / "olist_products_dataset.parquet")


df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32951 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 3.7 MB

In [ ]:
display(olist_products.describe(include="all"))

In [ ]:
df["product_category_name"].value_counts()["Unknown"]

sellers dataset.parquet

In [ ]:
sellers = pd.read_parquet(SILVER_PATH / "olist_sellers_dataset.parquet")

In [ ]:
sellers.info()
sellers.head()

In [ ]:
sellers.describe(include="all")

In [ ]:
sellers.isna().sum()

In [ ]:
sellers.duplicated().sum()

In [ ]:
sellers["seller_city"].str.startswith(" ").sum()

In [ ]:
sellers["seller_city"].str.endswith(" ").sum()

In [ ]:
sellers["seller_state"].str.startswith(" ").sum()

In [ ]:
sellers["seller_state"].str.endswith(" ").sum()

In [ ]:
sellers.info()

product_category_name_translation.parquet

In [ ]:

product_category_name = pd.read_parquet(SILVER_PATH / "product_category_name_translation.parquet")

product_category_name.info()

display(product_category_name.head())

In [ ]:
display(product_category_name.describe(include="all"))

In [ ]:
product_category_name.isna().sum()

product_category_name.duplicated().sum()

In [ ]:
product_category_name["product_category_name"].str.startswith(" ").sum()
product_category_name["product_category_name"].str.endswith(" ").sum()

In [ ]:
product_category_name["product_category_name_english"].str.startswith(" ").sum()
product_category_name["product_category_name_english"].str.endswith(" ").sum()

olist_order_payments_dataset.parquet

In [ ]:
order_payments = pd.read_parquet(SILVER_PATH /"olist_order_payments_dataset.parquet")

order_payments.info()

display(order_payments.head())

In [ ]:
display(order_payments.describe(include="all"))

In [ ]:

order_payments.isna().sum()

order_payments.duplicated().sum()

In [ ]:
order_payments["payment_type"].str.startswith(" ").sum()
order_payments["payment_type"].str.endswith(" ").sum()

In [ ]:
# order_payments["payment_installments"].min()
order_payments["payment_installments"].max()

In [ ]:


(order_payments["payment_value"] < 0).sum()

(order_payments["payment_installments"] <= 0).sum()

In [ ]:
(order_payments["payment_installments"] <= 0).sum()

In [ ]:
order_payments[order_payments["payment_installments"] <= 0]

In [ ]:
order_payments[
    order_payments["order_id"] == "744bade1fcf9ff3f31d860ace076d422"
]

In [ ]:
order_payments[
    order_payments["order_id"] == "1a57108394169c0b47d8f876acc9ba2d"
]

Data Quality Note:
Found 2 records where:
- payment_type = credit_card
- payment_installments = 0

These appear inconsistent and should be reviewed  before applying an automatic correction.

olist_order_reviews_dataset ======================================

In [83]:
order_reviews = pd.read_parquet(SILVER_PATH /"olist_order_reviews_dataset.parquet")

In [84]:
order_reviews.info()
order_reviews.head()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  datetime64[us]
 6   review_answer_timestamp  99224 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(4)
memory usage: 14.2 MB

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

In [67]:
(order_reviews["review_score"] <= 0).sum()
(order_reviews["review_score"] > 5).sum()

np.int64(0)

In [73]:
# order_reviews.isna().sum()

order_reviews.duplicated().sum()

np.int64(0)

In [ ]:
order_reviews["review_id"].str.startswith(" ").sum()
order_reviews["order_id"].str.endswith(" ").sum()

np.int64(0)

In [77]:
# Convert dates temporarily for checking
order_reviews["review_creation_date"] = pd.to_datetime(order_reviews["review_creation_date"])

order_reviews["review_answer_timestamp"] = pd.to_datetime(order_reviews["review_answer_timestamp"])

In [78]:
# Seller answered BEFORE review was created
(
    order_reviews["review_answer_timestamp"]
    < order_reviews["review_creation_date"]
).sum()

np.int64(0)

In [80]:
order_reviews[
    order_reviews["review_answer_timestamp"]
    < order_reviews["review_creation_date"]
]

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []

In [81]:
print("Review Creation Date")
print(order_reviews["review_creation_date"].min())
print(order_reviews["review_creation_date"].max())

print()

print("Review Answer Date")
print(order_reviews["review_answer_timestamp"].min())
print(order_reviews["review_answer_timestamp"].max())

Review Creation Date
2016-10-02 00:00:00
2018-08-31 00:00:00

Review Answer Date
2016-10-07 18:32:28
2018-10-29 12:27:35

In [82]:
order_reviews[
    ["review_creation_date", "review_answer_timestamp"]
].isna().sum()

review_creation_date       0
review_answer_timestamp    0
dtype: int64

olist_geolocation_dataset  =================================

In [13]:
olist_geolocation = pd.read_parquet(SILVER_PATH /"olist_geolocation_dataset.parquet")

In [14]:
olist_geolocation.info()
olist_geolocation.head()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 50.1 MB

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [15]:
olist_geolocation.duplicated().sum()

np.int64(261831)

In [16]:
olist_geolocation.describe(include="all")

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
count,1.000163e+06,1.000163e+06,1.000163e+06,1000163,1000163
unique,NaN,NaN,NaN,8011,27
top,NaN,NaN,NaN,sao paulo,SP
freq,NaN,NaN,NaN,135800,404268
mean,3.657417e+04,-2.117615e+01,-4.639054e+01,NaN,NaN
std,3.054934e+04,5.715866e+00,4.269748e+00,NaN,NaN
min,1.001000e+03,-3.660537e+01,-1.014668e+02,NaN,NaN
25%,1.107500e+04,-2.360355e+01,-4.857317e+01,NaN,NaN
50%,2.653000e+04,-2.291938e+01,-4.663788e+01,NaN,NaN
75%,6.350400e+04,-1.997962e+01,-4.376771e+01,NaN,NaN
max,9.999000e+04,4.506593e+01,1.211054e+02,NaN,NaN

In [17]:
olist_geolocation.isna().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [25]:
# olist_geolocation["geolocation_city"].str.startswith(" ").sum()
olist_geolocation["geolocation_city"].str.endswith(" ").sum()

np.int64(1)

In [20]:
olist_geolocation[
    olist_geolocation.duplicated()
].head(20)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP
72,1046,-23.545320,-46.644069,sao paulo,SP
79,1050,-23.549854,-46.643139,sao paulo,SP
80,1032,-23.540775,-46.635515,sao paulo,SP
82,1046,-23.546081,-46.644820,sao paulo,SP
86,1048,-23.547449,-46.640169,são paulo,SP
89,1036,-23.541700,-46.641318,sao paulo,SP
91,1013,-23.547325,-46.634184,sao paulo,SP
94,1046,-23.546081,-46.644820,sao paulo,SP
95,1046,-23.546129,-46.642951,sao paulo,SP
97,1009,-23.546341,-46.636239,sao paulo,SP
102,1009,-23.546341,-46.636239,sao paulo,SP
104,1050,-23.549107,-46.644105,são paulo,SP
106,1047,-23.546273,-46.641225,sao paulo,SP
111,1032,-23.537020,-46.634359,sao paulo,SP
114,1005,-23.549819,-46.635606,sao paulo,SP

In [21]:
olist_geolocation[
    olist_geolocation.duplicated(keep=False)
].head(20)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
6,1047,-23.546273,-46.641225,sao paulo,SP
7,1013,-23.546923,-46.634264,sao paulo,SP
8,1029,-23.543769,-46.634278,sao paulo,SP
9,1011,-23.547640,-46.636032,sao paulo,SP
10,1013,-23.547325,-46.634184,sao paulo,SP
13,1012,-23.548946,-46.634671,sao paulo,SP
15,1046,-23.546081,-46.644820,sao paulo,SP
16,1039,-23.541883,-46.639919,sao paulo,SP
17,1024,-23.541390,-46.629899,são paulo,SP
18,1009,-23.546935,-46.636588,sao paulo,SP
19,1046,-23.545884,-46.643163,sao paulo,SP
20,1046,-23.545166,-46.643786,sao paulo,SP
21,1020,-23.552235,-46.628441,são paulo,SP
22,1011,-23.546690,-46.635447,são paulo,SP
24,1050,-23.549774,-46.645599,sao paulo,SP
25,1045,-23.541594,-46.641894,sao paulo,SP
27,1007,-23.550393,-46.637302,sao paulo,SP

In [ ]:
geo = pd.read_parquet("../output/silver/olist_geolocation_dataset.parquet")

geo.info()

geo.duplicated().sum()

geo["geolocation_city"].str.endswith(" ").sum()

geo["geolocation_zip_code_prefix"].head()

<class 'pandas.DataFrame'>
RangeIndex: 738332 entries, 0 to 738331
Data columns (total 5 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   geolocation_zip_code_prefix  738332 non-null  str
 1   geolocation_lat              738332 non-null  float64
 2   geolocation_lng              738332 non-null  float64
 3   geolocation_city             738332 non-null  str
 4   geolocation_state            738332 non-null  str
dtypes: float64(2), str(3)
memory usage: 40.5 MB

0    01037
1    01046
2    01046
3    01041
4    01035
Name: geolocation_zip_code_prefix, dtype: str